### ISSUE TITLE
Welcome screen logic

### ISSUE THREAD

**Issue by maksgithub** [maksgithub/TestRepository#18]
1. При запуску програми показати **тільки** наступне :
**Press E for exit
Press A for about**
Нічого крім цього тексту не повинно бути на екрані

2. При натисканні на клавішу E(велику або малу) - завершуємо роботу
3. При натисканні на клавішу A(велику або малу) - видаляємо все із консолі і показуємо:
**Project Name version 1.0.0.0
Press any key to return ...**
Нічого крім цього тексту не повинно бути на екрані
При натисканні на будь-яку клавішу - повертаємось до пункту 1

Потрібно створити бескінечний цикл `while(true) {}` в якому буде считуватись клавіша за допомогою `Console.ReadKey()` при натисканні клавіш зазначених у задачі - виконуюються відповідні операціїї
Екран очистити за допомогою `Console.Clear()`
[Тут показано приклад як використовувати Console.ReadKey()](https://www.dotnetheaven.com/article/console.readkey-method-in-csharp)

**Comment by marstester** [comment]
hello
