### ISSUE TITLE
Create users

### ISSUE THREAD

**Issue by maksgithub** [maksgithub/TestRepository#19]
### Додати можливість створювати користувачів
1. В основне діалогове вікно додати текст
_Text:_ **Press U to create user**
2. При натисканні на клавішу U:
Clear screen
_Text:_ **Write user name and press Enter key:** курсор на новий рядок
3. Додати валідацію після натискання на Enter: 
3.1. Якщо є інші символи (цифри або спаціальні символи) - виводимо на екран червоним кольром **Only characters are allowed** 
3.2. Якщо довжина більше 3 і менше 15 символів - виводимо на екран червоним кольром **Name must be longer than 3 characters and less than 15 characters** 
3.3. Якщо валідація не успішна - після червоного тексту пишемо:  **Preess Enter** і повертаємось до пункту 2
4. Після натискання на клавішу Enter повертаємося до основного меню

В рамках цієї задачі необхідно створити клас `User` із властивістю `Name`
Для того щоб зробити текст червоним використати `Console.ForegroundColor = ConsoleColor.Red;`
Для того щоб зробити текст білим використати `Console.ForegroundColor = ConsoleColor.White;`
Для знаходження довжини використати string Length
Для того щоб дызнатись чи є інші символи погуглити про `char.IsLetter()`;

**Comment by maksgithub** [comment]
Для знаходження довжини використати string `Length`

**Comment by Dimon2308** [comment]
Виконав перші 2 пункти, але в методі. Помню як додати новий клас, але не помню шо спочатку в нього записується, бо в Empty у мене пусто. І не помню чи можна записувати клас в класі чи він пишеться паралельно( на одному рівні з дужками класу program)?

**Comment by maksgithub** [comment]
Щоб побічити код в Empty потрібно зайти в git Extensions і зробити:
1. Спочатку створи нову бранчу за допомогою **Create Branch**
1. **Fetch All**
2. Правою кнопкою на origin/master (зеленим кольором написано) і **Merge into current branch**

Після цього з'явиться мій код

**Comment by maksgithub** [comment]
Клас можна створювати в різних місцях:
1. У іншому класі (але він буде видимий тільки в тому класі що ти створив)
2. На рівні іншого класу, наприклад клас Program
3. У іншому файлі. **І це самий правильний варіант**
3.1 Для цього потрібно правою кнопкою на твоєму проекті і **Add** => **Class**
3.2 [Як створити клас](https://www.youtube.com/watch?v=sgSiNZx3JBc)
4. [Тут написано про класи](https://metanit.com/sharp/tutorial/3.1.php)
